def _project_answer(message: str):
    text = message.lower()

    if "orchestrateur" in text or "orchestrator" in text:
        return (
            "L’orchestrateur IA coordonne les demandes entre plusieurs agents spécialisés, "
            "applique les règles de sécurité, choisit les bons outils et garde une trace "
            "des actions pour que l’entreprise conserve le contrôle."
        )

    if "validation humaine" in text or "human approval" in text:
        return (
            "La validation humaine permet de bloquer les actions sensibles avant exécution. "
            "L’IA prépare la demande, mais une personne autorisée décide si la modification "
            "peut être appliquée."
        )

    if "traçabilité" in text or "tracabilite" in text or "traceability" in text:
        return (
            "La traçabilité consiste à enregistrer les demandes, les décisions, les validations "
            "et les résultats d’exécution afin de pouvoir auditer le système après coup."
        )

    return None


def search_procedure(query: str):
    return {
        "query": query,
        "matched_document": "internal_procedure_mock.pdf",
        "summary": "This is a mock procedure result. Later this will search real company documents using RAG."
    }


def summarize_document(query: str):
    return {
        "document": "mock_document",
        "summary": "This is a mock document summary generated by the Knowledge Agent."
    }


def answer_policy_question(query: str):
    return {
        "question": query,
        "answer": "This is a mock policy answer. Later this will be retrieved from internal documentation."
    }


def run(message: str):
    text = message.lower()
    project_answer = _project_answer(message)

    if project_answer:
        return {
            "agent": "knowledge_agent",
            "parser_source": "knowledge_fallback",
            "parsed_action": "answer_knowledge_question",
            "tool_used": "knowledge_project_answer",
            "result": {
                "answer": project_answer,
            },
            "response": project_answer,
            "message": project_answer,
        }

    if "procedure" in text or "procédure" in text:
        return {
            "agent": "knowledge",
            "tool_used": "search_procedure",
            "result": search_procedure(message)
        }

    if "summarize" in text or "résume" in text or "resume" in text:
        return {
            "agent": "knowledge",
            "tool_used": "summarize_document",
            "result": summarize_document(message)
        }

    if "policy" in text or "politique" in text:
        return {
            "agent": "knowledge",
            "tool_used": "answer_policy_question",
            "result": answer_policy_question(message)
        }

    return {
        "agent": "knowledge",
        "tool_used": "none",
        "result": "Knowledge Agent received the request but no specific tool matched."
    }
