def search_procedure(query: str):
    return {
        "query": query,
        "matched_document": "internal_procedure_mock.pdf",
        "summary": "This is a mock procedure result. Later this will search real company documents using RAG."
    }


def summarize_document(query: str):
    return {
        "document": "mock_document",
        "summary": "This is a mock document summary generated by the Knowledge Agent."
    }


def answer_policy_question(query: str):
    return {
        "question": query,
        "answer": "This is a mock policy answer. Later this will be retrieved from internal documentation."
    }


def run(message: str):
    text = message.lower()

    if "procedure" in text or "procédure" in text:
        return {
            "agent": "knowledge",
            "tool_used": "search_procedure",
            "result": search_procedure(message)
        }

    if "summarize" in text or "résume" in text or "resume" in text:
        return {
            "agent": "knowledge",
            "tool_used": "summarize_document",
            "result": summarize_document(message)
        }

    if "policy" in text or "politique" in text:
        return {
            "agent": "knowledge",
            "tool_used": "answer_policy_question",
            "result": answer_policy_question(message)
        }

    return {
        "agent": "knowledge",
        "tool_used": "none",
        "result": "Knowledge Agent received the request but no specific tool matched."
    }